version: '3.1'

services:
  redis-service:
    image: redis
    restart: always
    volumes:
      - ./storage/redis/data:/data
    expose:
      - 6379
    logging:
      driver: none

  db-service:
    image: postgres:10.4
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
    logging:
      driver: none

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    depends_on:
      - db-service
    env_file:
      - ./.env
    expose:
      - 3000

  finance-management-service:
    container_name: finance-management-service
    build:
      context: ./finance-management-service
      dockerfile: Dockerfile
    depends_on:
      - db-service
    env_file:
      - ./.env
    expose:
      - 3000

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 80
    links:
      - auth-service

  nginx-service:
    restart: always
    container_name: nginx-service
    build:
      context: ./nginx-service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '80:80'
    links:
      - auth-service
      - frontend
