version: '3.1'

services:
  nginx-service:
    restart: always
    build:
      context: ./nginx-service
    ports:
      - '80:80'
    links:
      - auth-service
  redis-service:
    image: redis
    restart: always
    volumes:
      - ./storage/redis/data:/data
    expose:
      - 6379
    logging:
      driver: none
  db-service:
    image: postgres:10.4
    expose:
      - 5432
    env_file:
      - ./auth-account-koa-config/variables/dev.env
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
    logging:
      driver: none
  auth-service:
    build:
      context: ./auth-service
    depends_on:
      - db-service
    env_file:
      - ./auth-account-koa-config/variables/dev.env
    environment:
      AUTH_PORT: 3000
      DATABASE_URL: postgres://user:pass@db-service:5432/db
      REDIS_HOST: redis://redis-service
    expose:
      - 3000
