openapi: "3.0.0"

info:
  description: This package defines the Auth service.
  title: Auth Service
  version: 1.0.0
  license:
    name: MIT

paths:
  "/api/auth/sign-up":
    post:
      summary: Create a user
      operationId: createUser
      tags:
      - user
      requestBody:
        description: The user information
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SignUpUser"
        required: true
      responses:
        "201":
          description: Saved user
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SignUpUserResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
  "/api/auth/sign-in":
    post:
      summary: Sign In with credentials
      operationId: signInAuth
      tags:
      - auth
      requestBody:
        description: The user's credentials
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SignInUser"
        required: true
      responses:
        "200":
          description: Successfully signed in
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SignInUserResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"

  "/api/auth/sessions":
    post:
      summary: Create session
      operationId: postSession
      tags:
      - session
      security:
        - bearerAuth: []
      requestBody:
        description: The session's data
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PostSession"
        required: true
      responses:
        "200":
          description: Session was created successfully
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PostSessionResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"

  "/api/auth/sessions/{sessionId}":
    get:
      summary: Get session by ID
      operationId: getSession
      tags:
      - session
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          description: The id of the session to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Info for a specific session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSessionResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    delete:
      summary: Delete session by ID
      operationId: deleteSession
      tags:
      - session
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          description: The id of the session to delete
          schema:
            type: string
      responses:
        "204":
          description: The session was deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  "/api/auth/users":
    get:
      summary: Get users
      operationId: getUsers
      tags:
      - user
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
        - name: skip
          in: query
          description: How many items should be skipped
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of users
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/GetUsersResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"

  "/api/auth/docs":
    get:
      responses:
        "200":
          description: A docs for Auth Service
          content:
            text/html:
              schema:
                type: string


components:
  schemas:
    UserId:
      type: string
      format: uuid
    UserEmail:
      type: string
      format: email
    UserPassword:
      type: string
      format: password
      minLength: 6
      maxLength: 20
    UserRole:
      type: string
      enum: [ADMIN, USER, GUEST]
    FullUser:
      required:
        - id
        - username
        - email
        - firstName
        - lastName
        - password
        - role
      properties:
        id:
          "$ref": "#/components/schemas/UserId"
        username:
          type: string
        email:
          "$ref": "#/components/schemas/UserEmail"
        firstName:
          type: string
        lastName:
          type: string
        password:
          "$ref": "#/components/schemas/UserPassword"
        role:
          "$ref": "#/components/schemas/UserRole"
    SafeUser:
      required:
        - id
        - username
        - email
        - firstName
        - lastName
        - role
      properties:
        id:
          "$ref": "#/components/schemas/UserId"
        username:
          type: string
        email:
          "$ref": "#/components/schemas/UserEmail"
        firstName:
          type: string
        lastName:
          type: string
        role:
          "$ref": "#/components/schemas/UserRole"
    SaveUsers:
      type: array
      items:
        "$ref": "#/components/schemas/SafeUser"

    SignUpUser:
      required:
      - data
      properties:
        data:
          required:
          - username
          - email
          - firstName
          - lastName
          - password
          - role
          properties:
            username:
              type: string
            email:
              "$ref": "#/components/schemas/UserEmail"
            firstName:
              type: string
            lastName:
              type: string
            password:
              "$ref": "#/components/schemas/UserPassword"
            role:
              "$ref": "#/components/schemas/UserRole"
    SignUpUserResponse:
      required:
      - data
      properties:
        data:
          required:
          - session
          - user
          properties:
            session:
              "$ref": "#/components/schemas/Session"
            user:
              "$ref": "#/components/schemas/SafeUser"

    SignInUser:
      required:
      - data
      properties:
        data:
          required:
          - username
          - password
          properties:
            username:
              type: string
            password:
              "$ref": "#/components/schemas/UserPassword"
    SignInUserResponse:
      required:
      - data
      properties:
        data:
          required:
          - session
          - user
          properties:
            session:
              "$ref": "#/components/schemas/Session"
            user:
              "$ref": "#/components/schemas/SafeUser"

    GetUsersResponse:
      required:
      - data
      properties:
        data:
          required:
          - users
          properties:
            users:
              "$ref": "#/components/schemas/SaveUsers"

    Session:
      required:
      - id
      - userId
      - serviceId
      - serviceToken
      - expiryDate
      properties:
        id:
          type: string
          format: uuid
        userId:
          "$ref": "#/components/schemas/UserId"
        serviceId:
          type: string
          format: uuid
        serviceToken:
          type: string
        expiryDate:
          type: integer
          format: int32
    PostSession:
      required:
      - data
      properties:
        data:
          required:
          - serviceId
          properties:
            serviceId:
              type: string
              format: uuid
    PostSessionResponse:
      required:
      - data
      properties:
        data:
          required:
          - session
          properties:
            session:
              "$ref": "#/components/schemas/Session"
    GetSessionResponse:
      required:
      - data
      properties:
        data:
          required:
          - session
          properties:
            session:
              "$ref": "#/components/schemas/Session"

    Error:
      required:
      - errors
      - message
      properties:
        errors:
          type: array
          items:
            type: string
        message:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
