openapi: "3.0.0"

info:
  description: This package defines the Audit service.
  title: Audit Service
  version: 1.0.0
  license:
    name: MIT

paths:
  "/auth/sign-up":
    post:
      summary: Create a user
      operationId: createUser
      tags:
      - user
      requestBody:
        description: The user information
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SignUpUser"
        required: true
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
  "/users":
    get:
      summary: Get users
      operationId: getUsers
      tags:
      - user
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
        - name: skip
          in: query
          description: How many items should be skipped
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of users
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/SaveUsers"
                
components:
  schemas:
    UserRole:
      type: string
      enum: [ADMIN, USER, GUEST]
    FullUser:
      required:
        - id
        - username
        - email
        - firstName
        - lastName
        - role
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        role:
          type: string
    SignUpUser:
      required:
      - username
      - email
      - firstName
      - lastName
      - password
      - role
      properties:
        username:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        role:
          "$ref": "#/components/schemas/UserRole"
    SafeUser:
      required:
        - username
        - email
        - firstName
        - lastName
        - id
      properties:
        username:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        id:
          type: string
        role:
          "$ref": "#/components/schemas/UserRole"
    SaveUsers:
      type: array
      items:
        "$ref": "#/components/schemas/SafeUser"
    Error:
      required:
      - errors
      - message
      properties:
        errors:
          type: array
          items:
            type: string
        message:
          type: string