version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 35432:35432
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local