# Use root/password as user/password credentials
version: '3.1'

services:

  db:
    image: postgres:10.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ../storage/postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
