version: '3.1'

services:
  redis-service:
    image: redis
    restart: always
    volumes:
      - ../storage/redis/data:/data
    expose:
      - 6379
    ports:
      - 6379:6379
    logging:
      driver: none
